### ISSUE TITLE
Inflection of ID causes issues in Rails apps

### ISSUE THREAD

**Issue by bcardarella** [skryl/qbxml#2]
You should avoid inflecting common words like 'id' because `String#camelize` rely upon the inflection. We have several migrations that have 'Id' in the name of the migration. This inflection breaks those migrations now.

**Comment by skalee** [comment]
This is still broken on master.

Given example, I have Rails migration in `db/migrate/TIMESTAMP_add_user_id_to_invoices.rb`. After adding qbxml to Gemfile, this migration fails. In order to get it working, I need to rename migration class defined in this file from `AddUserIdToInvoices` to `AddUserIDToInvoices` (ID in upper case).

If, for some reason, this is hard to fix, I suggest adding [post install message to gemspec](http://guides.rubygems.org/specification-reference/#post_install_message).
